import { Template } from '@/types/message';

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'tpl-01-single-promo',
    name: '01 Single Promotion Artwork',
    description: 'รูปภาพโปรโมชั่นเดี่ยวความละเอียดสูง เหมาะสำหรับประกาศแคมเปญด่วน Flash Sale',
    category: 'promotion',
    messageType: 'image',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      originalContentUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1040&auto=format&fit=crop&q=80',
      previewImageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
      altText: 'โปรโมชั่นพิเศษประจำเดือน ช้อปด่วนจำกัดเวลา',
      destinationUrl: 'https://myshop.line.me/promotion',
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-02-4zone-imagemap',
    name: '02 4-Zone Clickable Promotion',
    description: 'ภาพ Artwork เดียวแบ่ง 4 โซนคลิก แยกไปยังสินค้าหรือหมวดหมู่ต่างๆ 4 ลิงก์',
    category: 'promotion',
    messageType: 'imagemap',
    thumbnailUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      baseUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1040&auto=format&fit=crop&q=80',
      altText: 'แคมเปญ 4 สินค้าขายดีประจำสัปดาห์',
      baseSize: {
        width: 1040,
        height: 1040,
      },
      actions: [
        {
          id: 'zone-1',
          label: 'สินค้า A (บนซ้าย)',
          x: 0,
          y: 0,
          width: 520,
          height: 520,
          actionType: 'uri',
          uri: 'https://myshop.line.me/product-a',
        },
        {
          id: 'zone-2',
          label: 'สินค้า B (บนขวา)',
          x: 520,
          y: 0,
          width: 520,
          height: 520,
          actionType: 'uri',
          uri: 'https://myshop.line.me/product-b',
        },
        {
          id: 'zone-3',
          label: 'สินค้า C (ล่างซ้าย)',
          x: 0,
          y: 520,
          width: 520,
          height: 520,
          actionType: 'uri',
          uri: 'https://myshop.line.me/product-c',
        },
        {
          id: 'zone-4',
          label: 'สินค้า D (ล่างขวา)',
          x: 520,
          y: 520,
          width: 520,
          height: 520,
          actionType: 'uri',
          uri: 'https://myshop.line.me/product-d',
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-03-single-product',
    name: '03 Single Product Card',
    description: 'การ์ดสินค้าเดี่ยวแบบ Flex พร้อมรูปภาพ ป้ายโปรโมชั่น ราคาพิเศษ และปุ่มสั่งซื้อ',
    category: 'product',
    messageType: 'flex_card',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      heroImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
      heroAspectRatio: '20:13',
      badge: 'NEW ARRIVAL',
      headline: 'Nike Air Max Red Edition',
      subheadline: 'รองเท้าวิ่งรุ่นลิมิเต็ด เบาสบาย นุ่มเท้า',
      description: 'รองรับการซับแรงกระแทกขั้นสูง ดีไซน์สตรีทแฟชั่นยอดนิยม พร้อมรับประกันแท้ 100%',
      originalPrice: '4,500',
      salePrice: '3,290',
      currencySymbol: '฿',
      ctaLabel: 'ช้อปเลย',
      ctaUrl: 'https://myshop.line.me/nike-air-max',
      ctaColor: '#06C755',
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-04-product-carousel',
    name: '04 Product Carousel (4 Cards)',
    description: 'แคตตาล็อกสินค้าแบบเลื่อนสไลด์ (Swipe) เหมาะสำหรับแนะนำสินค้า 4-12 รายการ',
    category: 'ecommerce',
    messageType: 'flex_carousel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      altText: 'รวมสินค้าไฮไลต์ยอดนิยม ลดสูงสุด 50%',
      cards: [
        {
          id: 'card-1',
          heroImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
          heroAspectRatio: '20:13',
          badge: 'BEST SELLER',
          headline: 'Premium Wireless Headphones',
          subheadline: 'ตัดเสียงรบกวน Active Noise Cancelling',
          description: 'แบตเตอรี่ใช้งานต่อเนื่อง 40 ชั่วโมง เสียงเบสหนักสะใจ',
          originalPrice: '2,990',
          salePrice: '1,890',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/headphones',
          ctaColor: '#06C755',
        },
        {
          id: 'card-2',
          heroImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
          heroAspectRatio: '20:13',
          badge: 'HOT',
          headline: 'Minimalist Smart Watch',
          subheadline: 'วัดอัตราการเต้นหัวใจ กันน้ำระดับ 5ATM',
          description: 'หน้าจอ AMOLED คมชัด แบตเตอรี่อึดนาน 14 วัน',
          originalPrice: '1,990',
          salePrice: '1,290',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/smart-watch',
          ctaColor: '#06C755',
        },
        {
          id: 'card-3',
          heroImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
          heroAspectRatio: '20:13',
          badge: 'SALE 30%',
          headline: 'Classic UV Sunglasses',
          subheadline: 'กันแดด UV400 ถนอมสายตา',
          description: 'กรอบน้ำหนักเบา ทนทาน ไม่กดทับจมูก ใส่สบายทุกโอกาส',
          originalPrice: '1,490',
          salePrice: '990',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/sunglasses',
          ctaColor: '#06C755',
        },
        {
          id: 'card-4',
          heroImage: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
          heroAspectRatio: '20:13',
          badge: 'TRENDING',
          headline: 'Studio Gaming Microphone',
          subheadline: 'เสียงคมชัดระดับพ็อดแคสต์ เสียบใช้งานได้ทันที',
          description: 'ระบบตัดเสียงรบกวนรอบข้าง ปรับไฟ RGB ได้สวยงาม',
          originalPrice: '2,290',
          salePrice: '1,590',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/gaming-mic',
          ctaColor: '#06C755',
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-05-hero-carousel',
    name: '05 Campaign Hero + Product Carousel',
    description: 'ลำดับ 2 ข้อความ: ภาพ Banner แคมเปญขนาดใหญ่ + แคตตาล็อกสินค้าสไลด์ด้านล่าง',
    category: 'promotion',
    messageType: 'hero_carousel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      heroArtworkUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=1040&auto=format&fit=crop&q=80',
      heroDestinationUrl: 'https://myshop.line.me/payday-sale',
      altText: 'แคมเปญ Payday Sale ลดทั้งร้านสูงสุด 70%',
      cards: [
        {
          id: 'card-1',
          heroImage: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80',
          badge: 'FLASH DEAL',
          headline: 'Apple Watch Series 9',
          subheadline: 'ชิป S9 SiP เร็วแรง แบตเตอรี่ใช้งานได้ทั้งวัน',
          originalPrice: '15,900',
          salePrice: '13,900',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/apple-watch',
        },
        {
          id: 'card-2',
          heroImage: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&auto=format&fit=crop&q=80',
          badge: 'HIT',
          headline: 'iPhone 15 Pro Max Case',
          subheadline: 'เคสกันกระแทกเกรดพรีเมียม รองรับ MagSafe',
          originalPrice: '1,290',
          salePrice: '790',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/phone-case',
        },
        {
          id: 'card-3',
          heroImage: 'https://images.unsplash.com/photo-1629367494173-c78a56567877?w=800&auto=format&fit=crop&q=80',
          badge: '1 แถม 1',
          headline: 'Fast Charging Cable 2M',
          subheadline: 'สายชาร์จถักไนลอนทนทาน ชาร์จเร็ว 65W',
          originalPrice: '690',
          salePrice: '390',
          ctaLabel: 'ช้อปเลย',
          ctaUrl: 'https://myshop.line.me/cables',
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-06-text-artwork',
    name: '06 Text + Campaign Artwork',
    description: 'ลำดับ 2 ข้อความ: ข้อความทักทายพร้อมสิทธิประโยชน์ + ภาพโปสเตอร์กิจกรรม',
    category: 'announcement',
    messageType: 'mixed',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      altText: 'ประกาศแคมเปญพิเศษสำหรับสมาชิก',
      blocks: [
        {
          id: 'blk-1',
          type: 'text',
          content: {
            text: '🎉 สิทธิพิเศษสำหรับเพื่อนคนสำคัญบน LINE OA!\n\nวันนี้รับคูปองส่วนลดพิเศษ 100 บาท เมื่อช้อปครบ 800 บาท เพียงคลิกดูรายละเอียดที่ภาพด้านล่างนี้ได้เลยค่ะ 👇',
          },
        },
        {
          id: 'blk-2',
          type: 'image',
          content: {
            originalContentUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1040&auto=format&fit=crop&q=80',
            previewImageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=600&auto=format&fit=crop&q=80',
            altText: 'คูปองส่วนลด 100 บาท',
            destinationUrl: 'https://myshop.line.me/coupon-claim',
          },
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-07-lookbook-carousel',
    name: '07 Fashion & Product Lookbook (1:1 Square)',
    description: 'รูปภาพสินค้าล้วนแบบสไลด์ สัดส่วน 1:1 จัตุรัส แตะที่รูปเพื่อเปิดหน้ารายการสินค้านั้นๆ',
    category: 'ecommerce',
    messageType: 'image_carousel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      altText: 'คอลเลกชันสินค้าแฟชั่น Lookbook ประจำฤดูกาล',
      aspectRatio: '1:1',
      cards: [
        {
          id: 'img-1',
          imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/look-1',
          label: 'Summer Look 01',
        },
        {
          id: 'img-2',
          imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/look-2',
          label: 'Urban Casual 02',
        },
        {
          id: 'img-3',
          imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/look-3',
          label: 'Minimalist Chic 03',
        },
        {
          id: 'img-4',
          imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/look-4',
          label: 'Autumn Classic 04',
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tpl-08-poster-carousel',
    name: '08 Multi-Poster Promotion (16:9 Banner)',
    description: 'แบนเนอร์ภาพโปรโมชั่นแนวนอนเลื่อนดูเต็มจอ เหมาะสำหรับรวม 3-5 กิจกรรมพิเศษ',
    category: 'promotion',
    messageType: 'image_carousel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=600&auto=format&fit=crop&q=80',
    defaultContent: {
      altText: 'รวมโปรโมชั่นและดีลพิเศษประจำสัปดาห์',
      aspectRatio: '16:9',
      cards: [
        {
          id: 'banner-1',
          imageUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=1040&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/deal-1',
          label: 'ดีลที่ 1: ลด 50%',
        },
        {
          id: 'banner-2',
          imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1040&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/deal-2',
          label: 'ดีลที่ 2: 1 แถม 1',
        },
        {
          id: 'banner-3',
          imageUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1040&auto=format&fit=crop&q=80',
          actionType: 'uri',
          uri: 'https://myshop.line.me/deal-3',
          label: 'ดีลที่ 3: ส่งฟรีทั่วไทย',
        },
      ],
    },
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
  },
];
